itportal/itportal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('weixin/', include('weixin.urls')),
    path('overview/', include('overview.urls')),
]

itportal/overview/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.urls import path
from . import views

app_name = 'overview'

urlpatterns = [
    path('', views.index, name='index'),
    path('host_monitordata', views.host_monitordata, name='host_monitordata'),
    path('user_expire', views.user_expire, name='user_expire'),
    path('user_expire/savedata', views.savedata_manager, name='savedata_manager')
]

itportal/weixin/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django.urls import path

from . import views

urlpatterns = [
    path('', views.hello, name='hello'),
]

itportal/overview/models.py
from django.db import models


# Create your models here.

class host_notmonitor(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=100)
    ip = models.GenericIPAddressField()
    owner = models.CharField(max_length=30, null=True)
    department = models.CharField(max_length=20)
    state = models.IntegerField()
    deleted = models.BooleanField()
    joinTime = models.BigIntegerField()
    updateTime = models.BigIntegerField()


class UserExpire(models.Model):
    userid = models.CharField(max_length=20, unique=True)
    username = models.CharField(max_length=20)
    company = models.CharField(max_length=100, null=True)
    phone = models.CharField(max_length=20, null=True)
    email = models.EmailField(null=True)
    state = models.CharField(max_length=10, null=True)
    expiretime = models.DateTimeField(null=True)
    manager = models.EmailField(null=True)
    updatetime = models.DateTimeField(null=True)
    createtime = models.DateTimeField(null=True)
    usertype = models.CharField(max_length=20, null=True, default='Temp')

    class Meta:
        indexes = [
            models.Index(fields=['expiretime']),
            ]


class RisTempUser(models.Model):
    userid = models.CharField(max_length=20, primary_key=True)

itportal/weixin/models.py
from django.db import models

# Create your models here.

itportal/overview/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.http import JsonResponse
from overview.models import host_notmonitor, UserExpire
from data.data_monitor import monitor_expireuser
import json


# from data import data_monitor
# import json
# from django.core.serializers import serialize

# Create your views here.


def index(request):
    return render(request, "overview/index.html")


def host_monitordata(request):
    # data_list = data_monitor.monitor_data()
    # return HttpResponse(json.dumps(data_list))
    # res = serialize('json', host_notmonitor.objects.all(), fields=('id','name'))
    res = list(host_notmonitor.objects.all().values('id', 'name', 'ip', 'owner', 'department'))
    return JsonResponse(res, safe=False)


def user_expire(request):
    t_expireuser = monitor_expireuser()
    l_tempuser = list(t_expireuser)
    return JsonResponse(l_tempuser, safe=False)


def savedata_manager(request):
    if request.is_ajax():
        data = json.loads(request.body)
        t_id = data['id']
        manangeruser = data['manageruser']
        UserExpire.objects.filter(id=t_id).update(manager=manangeruser)
    return HttpResponse(0)

itportal/weixin/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse

def hello(request):
    return HttpResponse("Hello world ! ")

itportal/overview/templates/overview/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Sunac IT Portal{% endblock %}
{% block css %}
  <!-- DataTables -->
  <link rel="stylesheet" href="{% static 'adminlet/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
  <link rel="stylesheet" href="{% static 'adminlet/plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
  <link rel="stylesheet" href="{% static 'bootstrap-table-master/dist/bootstrap-table.min.css' %}">
  <style>
  #zy1{'background':'#F0E68C'}
  </style>
{% endblock %}

{% block breadcrumb %}
<!-- Content Header (Page header) -->
  <div class="col-sm-6">
    <h1 class="m-0 text-dark">Dashboard</h1>
  </div>
<!-- /.col -->
  <div class="col-sm-6">
    <ol class="breadcrumb float-sm-right">
      <li class="breadcrumb-item"><a href="#">Home</a></li>
      <li class="breadcrumb-item active">Dashboard</li>
    </ol>
  </div>
<!-- /.col -->
{% endblock %}

{% block content %}
  <!-- Main content -->

        <!-- Table row -->
        <div class="row">
          <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-info">
              <div class="inner">
                <h3>RIS</h3>

                <p>堡垒机系统</p>
              </div>
              <div class="icon">
                <i class="ion ion-bag"></i>
              </div>
              <a href="https://ris.sunac.com.cn" target=_blank class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
            </div>
          </div>
          <!-- ./col -->
          <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-success">
              <div class="inner">
                <h3>SYS<sup style="font-size: 20px"></sup></h3>

                <p>基础监控系统</p>
              </div>
              <div class="icon">
                <i class="ion ion-stats-bars"></i>
              </div>
              <a href="http://os.monitor.sunac.com.cn/zabbix.php?action=dashboard.view" target=_blank class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
            </div>
          </div>
          <!-- ./col -->
          <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-primary">
              <div class="inner">
                <h3>WIKI</h3>

                <p>Wiki系统</p>
              </div>
              <div class="icon">
                <i class="ion ion-person-add"></i>
              </div>
              <a href="https://rccfwiki.sunac.com.cn:8443" target=_blank class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
            </div>
          </div>
          <!-- ./col -->
          <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-warning">
              <div class="inner">
                <h3>LOG</h3>

                <p>日志监控系统</p>
              </div>
              <div class="icon">
                <i class="ion ion-pie-graph"></i>
              </div>
              <a href="http://log.monitor.sunac.com.cn:9000" target=_blank class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
            </div>
          </div>
          <!-- ./col -->
        </div>
        <!-- /.row -->
        <!-- /.Table row -->

        <!-- Small boxes (Search Host) -->
        <div class="row">
          <div class="col-12">
            <!-- /.card -->
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">查询未添加监控的服务器</h3>
              </div>
              <!-- /.card-header -->
              <div id="toolbarhost">
                <button id="search1" class="btn btn-primary">
                  查询
                </button>
              </div>
              <div class="card-body">
                <table id="example1"> </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
      <!-- /.col -->
        </div>
        <!-- /.row -->
        <!-- /.Small boxes (Search Host) -->


        <!-- Small boxes (Search ExtUser) -->
        <div class="row">
          <div class="col-12">
            <!-- /.card -->
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">查询外部用户的过期时间<br/>注：临时账号过期后，会发送邮件给被通知人，请填写内部员工邮箱地址且仅允许一人</h3>
              </div>
              <!-- /.card-header -->
              <div id="toolbarextuser">
                <button id="search2" class="btn btn-primary">
                  查询
                </button>
              </div>
              <div class="card-body">
                <table id="example2"> </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
      <!-- /.col -->
        </div>
        <!-- /.row -->
        <!-- /.Small boxes (Search ExtUser) -->
    <!-- /.Main row -->


{% endblock %}

{% block script %}
<!-- DataTables -->
<script src="{% static 'adminlet/plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'adminlet/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'adminlet/plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'adminlet/plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
<script src="{% static 'bootstrap-table-master/dist/bootstrap-table.min.js' %}"></script>
<script src="{% static 'bootstrap-table-master/dist/bootstrap-table-locale-all.min.js' %}"></script>

<!-- page script -->
<script>
$(function (){
  $("#example1").bootstrapTable({
      cache: false,
      toolbar: "#toolbarhost",
      columns: [{
          field: 'id',
          title: '序号'
      }, {
          field: 'name',
          title: '主机名'
      }, {
          field: 'ip',
          title: 'IP地址',
          visible: false
      }, {
          field: 'owner',
          title: '负责人'
      }, {
          field: 'department',
          title: '部门'
      }]
    });

  $("#example2").bootstrapTable({
     cache: false,
     toolbar: "#toolbarextuser",
     columns: [{
         field: 'id',
         title: '序列'
     }, {
         field: 'username',
         title: '姓名'
     }, {
         field: 'company',
         title: '公司'
     }, {
         field: 'phone',
         title: '电话',
         visible: false
     }, {
         field: 'email',
         title: '邮箱',
         visible: false
     }, {
         field: 'status',
         title: '状态'
     }, {
         field: 'expiretime',
         title: '过期时间'
     }, {
         field: 'manager',
         title: '被通知人'
         }]
   });

  $('#search1').click(function (){
    $('#example1').bootstrapTable('destroy');
    $("#example1").bootstrapTable({
      url: "{% url "overview:host_monitordata" %}",
      method: "get",
      sidePagination: "client",
      pagination: true,
      pageNumber: 1,
      pageSize: 10,
      paginationPreText: "上一页",
      paginationNextText: "下一页",
      toolbar: "#toolbarhost",
      striped: true,
      search: true,
      sortable: true,
      sortOrder: "asc",
      sortName: "name",
      locale: "zh-CN",
      columns: [{
          field: 'id',
          title: '序号'
      }, {
          field: 'name',
          title: '主机名'
      }, {
          field: 'ip',
          title: 'IP地址',
          visible: false
      }, {
          field: 'owner',
          title: '负责人'
      }, {
          field: 'department',
          title: '部门'
      }]
    });
  });


  $('#search2').click(function (){
    $('#example2').bootstrapTable('destroy');
    $("#example2").bootstrapTable({
      url: "{% url "overview:user_expire" %}",
      method: "get",
      sidePagination: "client",
      pagination: true,
      pageNumber: 1,
      pageSize: 10,
      paginationPreText: "上一页",
      paginationNextText: "下一页",
      toolbar: "#toolbarextuser",
      striped: true,
      search: true,
      sortable: true,
      sortOrder: "asc",
      sortName: "name",
      locale: "zh-CN",
      columns: [{
          field: 'id',
          title: '序号',
          class: 'id'
      }, {
          field: 'username',
          title: '姓名'
      }, {
          field: 'company',
          title: '公司'
      }, {
          field: 'phone',
          title: '电话',
          visible: false
      }, {
          field: 'email',
          title: '邮箱',
          visible: false
      }, {
          field: 'state',
          title: '状态'
      }, {
          field: 'expiretime',
          title: '过期时间'
      }, {
          field: 'manager',
          title: '被通知人',
          class: 'editable'
      }, {
          title: '操作',
          field: 'operate',
          class: 'editOperate',
          formatter: formatterOperate
      }]
    });
  });
});

//格式化操作
function formatterOperate(value, row, index) {
	return `<button onclick='editRow(${index})' class='btn small blue'> 编辑</button >`;
}
// 新增行和编辑行时右侧操作改为保存和取消
let editFormatter = `<button onclick = 'saveRow(this)' class = 'btn small' > 保存 </button>
                     <button onclick='cancleRow(this)' class='btn small'>取消</button >`
//静默刷新
function refreshTable()
{
   $('#example2').bootstrapTable('refresh', {
       silent: true,
       url: '',
       query: ''
   });
        addKey = true;

    }

//保存数据
function saveRow(ele) {

	let obj = $(ele).parent().parent(); //获取tr的dom
	let saveKey = true; //是否允许保存
	let edit = obj.attr('data-edit') ? true : false; //是编辑还是添加
	let arrVal; //保存填入的数据
	obj.find('td.editable').each(function (index) {
	    let val = $(this).find('input').val().trim();
	    if (index < 1 && !val) saveKey = false; //姓名不能为空，否则不允许保存
	    arrVal = val
	})

	let manageruser = arrVal;
	let query;
	if (edit) { //修改编辑
	    let id = obj.find('td.id').text()
	    query = {
	        id,
	        manageruser
	    }
	} else { //新增添加
	    query = {
	        id,
	        manageruser
	    }
	}
  $.ajax({
            type: "post",
            url: "user_expire/savedata",
            data: JSON.stringify(query),
            contentType:'application/json',
            success:function(data) {  //接收后台返回的参数
                if(data==0) {
                    alert("数据保存成功")
                }
                else{
                    alert("数据保存失败")
                }
            },
            error:function (error) {
                console.log(error)
                alert(error)
            }
        })
	//发送数据成功后回调刷新
	refreshTable() //刷新
}
//开启编辑
function editRow(index) {
    console.log(index)
    $("#example2 tr:nth-child(" + (index + 1)).attr('data-edit', true) //编辑标志
    $("#example2 tr:nth-child(" + (index + 1) + ") td.editable").each(function () {
        var value = $(this).text();
        $(this).html("<input value='" + value + "'>");
    });
    $("#example2 tr:nth-child(" + (index + 1) + ") td.editOperate").html(editFormatter)
}

//取消编辑
function cancleRow(ele) {
    let obj = $(ele).parent().parent(); //获取tr的dom
    let edit = obj.attr('data-edit') ? true : false;
    if (edit) { //编辑状态回归
        refreshTable() //刷新
    }
}

</script>
{% endblock %}

itportal/overview/templates/overview/risdata.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {{ res }}

    <script>

        t = {{ res|safe }}
        console.log(t)

    </script>
</body>
</html>

itportal/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>{% block title %}融创IT门户 | Dashboard{% endblock %}</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'adminlet/plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Tempusdominus Bbootstrap 4 -->
  <link rel="stylesheet" href="{% static 'adminlet/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static 'adminlet/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <!-- JQVMap -->
  <link rel="stylesheet" href="{% static 'adminlet/plugins/jqvmap/jqvmap.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'adminlet/dist/css/adminlte.min.css' %}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static 'adminlet/plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{% static 'adminlet/plugins/daterangepicker/daterangepicker.css' %}">
  <!-- summernote -->
  <link rel="stylesheet" href="{% static 'adminlet/plugins/summernote/summernote-bs4.css' %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">


    {% block css %}{% endblock %}


</head>

<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
    </ul>


      </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="#" class="brand-link">
      <img src="{% static 'adminlet/dist/img/AdminLTELogo.png' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
           style="opacity: .8">
      <span class="brand-text font-weight-light">融创IT门户</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
{#      <div class="user-panel mt-3 pb-3 mb-3 d-flex">#}
{#        <div class="image">#}
{#          <img src="{% static 'adminlet/dist/img/user2-160x160.jpg' %}" class="img-circle elevation-2" alt="User Image">#}
{#        </div>#}
{#        <div class="info">#}
{#          <a href="#" class="d-block">Alexander Pierce</a>#}
{#        </div>#}
{#      </div>#}

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item">
            <a href="#" class="nav-link active">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Dashboard
{#                <i class="right fas fa-angle-left"></i>#}
              </p>
            </a>
            </ul>
          </li>

        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">

        {% block breadcrumb %}
        {% endblock %}

        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        {% block content %}{% endblock %}
      </div>
    </section>

  </div>

  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <strong>Sunac IT Portal</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 1.2.0
    </div>
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{% static 'adminlet/plugins/jquery/jquery.min.js' %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static 'adminlet/plugins/jquery-ui/jquery-ui.min.js' %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{% static 'adminlet/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- ChartJS -->
<script src="{% static 'adminlet/plugins/chart.js/Chart.min.js' %}"></script>
<!-- Sparkline -->
<script src="{% static 'adminlet/plugins/sparklines/sparkline.js' %}"></script>
<!-- JQVMap -->
{#<script src="{% static 'adminlet/plugins/jqvmap/jquery.vmap.min.js' %}"></script>#}
{#<script src="{% static 'adminlet/plugins/jqvmap/maps/jquery.vmap.usa.js' %}"></script>#}
<!-- jQuery Knob Chart -->
<script src="{% static 'adminlet/plugins/jquery-knob/jquery.knob.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'adminlet/dist/js/adminlte.js' %}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{% static 'adminlet/dist/js/pages/dashboard.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'adminlet/dist/js/demo.js' %}"></script>
<!-- summernote -->
<script src="{% static 'adminlet/plugins/summernote/summernote-bs4.min.js' %}"></script>
<!-- daterangepicker -->
<script src="{% static 'adminlet/plugins/moment/moment.min.js' %}"></script>
<script src="{% static 'adminlet/plugins/daterangepicker/daterangepicker.js' %}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{% static 'adminlet/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}"></script>
<!-- overlayScrollbars -->
<script src="{% static 'adminlet/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>

    {% block script %}{% endblock %}

</body>
</html>